// react-app/src/components/ArticleComment.tsx
import { Link } from "react-router-dom";
import type { Comment } from "../types";
import { useAuth } from "../auth/AuthContext";
import { defaultImage } from "../utils/defaultImage";

interface ArticleCommentProps {
  comment: Comment;
  onDelete: (comment: Comment) => void;
}

export default function ArticleComment({
  comment,
  onDelete,
}: ArticleCommentProps) {
  const { user } = useAuth();
  const canModify = user?.username === comment.author.username;
  const authorImage = defaultImage(comment.author.image);
  const formattedDate = new Date(comment.createdAt).toLocaleDateString(
    "en-US",
    { year: "numeric", month: "long", day: "numeric" },
  );

  return (
    <div className="card" data-testid="comment-card">
      <div className="card-block">
        <p className="card-text">{comment.body}</p>
      </div>
      <div className="card-footer">
        <Link
          className="comment-author"
          to={`/profile/${comment.author.username}`}
        >
          <img
            src={authorImage}
            className="comment-author-img"
            alt={comment.author.username}
          />
        </Link>
        &nbsp;
        <Link
          className="comment-author"
          to={`/profile/${comment.author.username}`}
        >
          {comment.author.username}
        </Link>
        <span className="date-posted">{formattedDate}</span>
        {canModify && (
          <span className="mod-options">
            <i
              className="ion-trash-a"
              data-testid="comment-delete"
              onClick={() => onDelete(comment)}
            ></i>
          </span>
        )}
      </div>
    </div>
  );
}

// src/app/features/article/components/article-comment.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output, inject } from '@angular/core';
import { UserService } from '../../../core/auth/services/user.service';
import { User } from '../../../core/auth/user.model';
import { RouterLink } from '@angular/router';
import { map } from 'rxjs/operators';
import { Comment } from '../models/comment.model';
import { AsyncPipe, DatePipe } from '@angular/common';
import { DefaultImagePipe } from '../../../shared/pipes/default-image.pipe';

@Component({
  selector: 'app-article-comment',
  template: `
    @if (comment) {
      <div class="card">
        <div class="card-block">
          <p class="card-text">
            {{ comment.body }}
          </p>
        </div>
        <div class="card-footer">
          <a class="comment-author" [routerLink]="['/profile', comment.author.username]">
            <img [src]="comment.author.image | defaultImage" class="comment-author-img" />
          </a>
          &nbsp;
          <a class="comment-author" [routerLink]="['/profile', comment.author.username]">
            {{ comment.author.username }}
          </a>
          <span class="date-posted">
            {{ comment.createdAt | date: 'longDate' }}
          </span>
          @if (canModify$ | async) {
            <span class="mod-options">
              <i class="ion-trash-a" (click)="delete.emit(true)"></i>
            </span>
          }
        </div>
      </div>
    }
  `,
  imports: [RouterLink, DatePipe, AsyncPipe, DefaultImagePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
/**
 * Renders a single comment card with author info, body text, and a delete icon.
 * The delete icon is only visible when the current user is the comment author.
 */
export class ArticleCommentComponent {
  @Input() comment!: Comment;
  /** Emits when the user clicks the delete icon. */
  @Output() delete = new EventEmitter<boolean>();

  /** Observable that resolves to true when the logged-in user authored this comment. */
  canModify$ = inject(UserService).currentUser.pipe(
    map((userData: User | null) => userData?.username === this.comment.author.username),
  );
}
